version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: adDaiko13
      MYSQL_DATABASE: empat-api
      MYSQL_USER: Admin
      MYSQL_PASSWORD: adDaiko13
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

  api:
    build: .
    container_name: my-spring-boot-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/empat-api
      SPRING_DATASOURCE_USERNAME: Admin
      SPRING_DATASOURCE_PASSWORD: adDaiko13
    depends_on:
      - db
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
