version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=adDaiko13
      - MYSQL_DATABASE=empat-api
      - MYSQL_USER=root
      - MYSQL_PASSWORD=adDaiko13
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  api:
    build: .
    container_name: spring_api_container
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/empat-api
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=adDaiko13
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
